sudo: required
services: 
  - docker

berfore_install: 
  - docker build -t smucciArchitech/react-app -f Dockerfile.dev . 

script: 
  - docker run smucciArchitech/react-app npm run test -- --coverage 