sudo: required
language: generic 
services: 
  - docker

before_install: 
  - docker build -t smucciarchitech/react-app -f Dockerfile.dev . 

script: 
  - docker run smucciarchitech/react-app npm run test -- --coverage 